### ISSUE TITLE
Path Forward

### ISSUE THREAD

**Issue by pmarcellino** [rsalaza4/Python-for-Industrial-Engineering#3]
Roberto,

I just came across this very nice repository, and since it is very new, I am wondering if this is sort of a one time dump, or is this a project you plan to maintain for some time?

Thank you,
Peter

**Comment by rsalaza4** [comment]
Hello Peter,

Thanks for reaching out. This is a project that I am planning to maintain in the long run.

Any ideas, suggestions and/or improvements are more to welcome.

Thanks,
Roberto
