### ISSUE TITLE
Western Electric Rules

### ISSUE THREAD

**Issue by pmarcellino** [rsalaza4/Python-for-Industrial-Engineering#4]
The controll chart features in this package are very nice. Are there any plans to implement the western electric rules?

Thank you,
Peter

**Comment by rsalaza4** [comment]
Hello Peter,

Yes, here it is:

https://github.com/rsalaza4/Python-for-Industrial-Engineering/blob/master/Quality%20Control%20Charts/Process%20Stability%20Control%20-%20Western%20Electric.py

Thanks,
Roberto
